import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,X,DownloadSimple,Sun,Moon,CloudSun,CornersOut,Check,Leaf} from '@phosphor-icons/react';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/cormorant-garamond/latin-400-italic.css';
import {WaterScene} from './WaterScene';
import {AudioPlayer} from './AudioPlayer';
import {Resume} from './Resume';
import {profile,projects} from './content';
const asset=p=>`${import.meta.env.BASE_URL}${p}`;
const nowMinutes=()=>{const d=new Date();return d.getHours()*60+d.getMinutes();};
const timeText=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
const readRoute=()=>location.hash.replace(/^#\/?/,'');
const phase=m=>m<330||m>=1260?{name:'月夜',en:'Moonlit silence',icon:Moon}:m<480?{name:'晨光',en:'The first quiet light',icon:CloudSun}:m<1020?{name:'日间',en:'A moment, in the light',icon:Sun}:{name:'黄昏',en:'A little golden hour',icon:CloudSun};
function TimePanel({minutes,setMinutes,manual,setManual}){const presets=[['晨光','Dawn',390],['日间','Daylight',720],['黄昏','Golden hour',1120],['月夜','Moonlight',1380]];return <div className="time-panel"><span className="eyebrow">A DIFFERENT KIND OF TIME</span><h1>追随光，<em>停留片刻。</em></h1><p className="serif-subtitle">Chase the light.</p><div className="time-instrument"><div className="time-readout"><label htmlFor="clock-input">{manual?'此刻的光影':'本地时间'}</label><input id="clock-input" type="time" value={timeText(minutes)} onChange={e=>{if(e.target.value){const [h,m]=e.target.value.split(':').map(Number);setMinutes(h*60+m);setManual(true)}}}/><span>{phase(minutes).name}</span></div><div className="ruler" onWheel={e=>{setMinutes(m=>(m+(e.deltaY>0?5:-5)+1440)%1440);setManual(true)}}><div className="ruler-marks" aria-hidden="true">{Array.from({length:25},(_,i)=><i key={i} className={i%6===0?'major':''}/>)}</div><input aria-label="光影时间" type="range" min="0" max="1439" step="1" value={minutes} onChange={e=>{setMinutes(Number(e.target.value));setManual(true)}}/><div className="ruler-cursor" style={{top:`${100-minutes/1439*100}%`}} aria-hidden="true"/></div><button className="back-now" onClick={()=>{setMinutes(nowMinutes());setManual(false)}}>回到现在 <ArrowRight size={14}/></button></div><div className="time-presets">{presets.map(([cn,en,m])=><button key={cn} className={phase(minutes).name===cn?'active':''} onClick={()=>{setMinutes(m);setManual(true)}}><span>{cn}</span><small>{en}</small></button>)}</div><p className="time-hint">拖动刻度或滚动，看看一天里的光。</p></div>}
function About(){return <div className="about-content"><span className="eyebrow">A LITTLE ABOUT ME</span><div className="about-heading"><h1>谢沛霖。</h1><span>Peilin Xie</span></div><img className="about-portrait" src={asset('portrait.jpg')} alt="谢沛霖证件照"/><p className="about-intro">{profile.introduction}</p><p>用数据理解问题，用 AI 把想法变成可以使用的产品。<br/>在分析与创造之间，认真完成每一次从想法到落地的探索。</p><p className="about-signature">Think clearly. Make it real.</p><div className="about-links"><a href="#/resume">完整简历 <ArrowUpRight size={16}/></a><a href="#/work">查看作品 <ArrowRight size={16}/></a></div><a className="about-mail" href={`mailto:${profile.email}`}>{profile.email}</a></div>}
function Work(){return <div className="work-content"><span className="eyebrow">IDEAS, MADE TANGIBLE</span><h1>一些想法，<em>已经发生。</em></h1><p className="view-description">AI 应用、Agent 工作流，与数据科学的六次实践。</p><div className="work-list">{projects.map((p,i)=><a className="work-row" href={`#/work/${p.id}`} key={p.id}><span className="work-number">0{i+1}</span><img src={asset('projects/'+p.images[0])} alt={p.name+'实际界面'} loading="lazy"/><div><h2>{p.name}</h2><p>{p.tagline}</p><span>{p.category} · {p.state}</span></div><ArrowUpRight size={21} weight="light"/></a>)}</div><p className="work-foot">所有展示均来自实际项目 · 点击进入，了解背后的问题与实现</p></div>}
function ProjectDetail({project:p,onLightbox,onVideo}){const [index,setIndex]=useState(0),touch=useRef(null);const change=d=>setIndex(i=>(i+d+p.images.length)%p.images.length);useEffect(()=>()=>onVideo(false),[]);return <div className="project-content"><a className="back-link" href="#/work"><ArrowLeft size={16}/>全部作品</a><div className="project-heading"><span className="eyebrow">{p.category} / {p.state}</span><h1>{p.name}</h1><p>{p.tagline}</p></div><div className="project-layout"><div className="project-visual"><div className="project-image" tabIndex="0" role="group" aria-label="项目截图，左右方向键翻页" onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();change(e.key==='ArrowLeft'?-1:1)}}} onTouchStart={e=>touch.current=[e.touches[0].clientX,e.touches[0].clientY]} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current[0],dy=e.changedTouches[0].clientY-touch.current[1];if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))change(dx<0?1:-1);touch.current=null;}}><button aria-label="放大当前截图" onClick={()=>onLightbox({src:asset('projects/'+p.images[index]),label:p.imageLabels[index]})}><img src={asset('projects/'+p.images[index])} alt={`${p.name} · ${p.imageLabels[index]}`}/><CornersOut className="expand-mark" size={20}/></button></div><div className="image-controls"><button aria-label="上一张截图" onClick={()=>change(-1)}><ArrowLeft size={19}/></button><span>{p.imageLabels[index]}<small>0{index+1} / 0{p.images.length}</small></span><button aria-label="下一张截图" onClick={()=>change(1)}><ArrowRight size={19}/></button></div><div className="image-dots">{p.images.map((img,i)=><button key={img} aria-label={`查看第 ${i+1} 张截图`} aria-pressed={i===index} className={i===index?'active':''} onClick={()=>setIndex(i)}><span/></button>)}</div>{p.video&&<video controls playsInline preload="none" poster={asset('projects/'+p.images[0])} onPlay={()=>onVideo(true)} onPause={()=>onVideo(false)} onEnded={()=>onVideo(false)} src={asset('projects/'+p.video)} aria-label={p.name+'演示视频'}/>}</div><div className="project-body"><p className="project-intro">{p.description}</p><section><h2>要解决的问题</h2><p>{p.problem}</p></section><section><h2>如何实现</h2><p>{p.approach}</p></section>{p.details.map(d=><section key={d.title}><h2>{d.title}</h2><p>{d.text}</p></section>)}<section><h2>技术栈</h2><p>{p.stack}</p></section><aside className="project-boundary"><span>当前状态与使用说明</span><p>{p.boundary}</p></aside><div className="project-links">{p.url&&<a href={p.url} target="_blank" rel="noreferrer">在线体验 <ArrowUpRight size={17}/></a>}{p.repo&&<a href={p.repo} target="_blank" rel="noreferrer">查看代码 <ArrowUpRight size={17}/></a>}</div></div></div></div>}
export function App(){
 const [route,setRoute]=useState(readRoute),[timeOpen,setTimeOpen]=useState(false),[minutes,setMinutes]=useState(nowMinutes),[manual,setManual]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[status,setStatus]=useState(''),[lightbox,setLightbox]=useState(null),[videoActive,setVideoActive]=useState(false);
 const dialog=useRef(null),scroll=useRef(null),savedScroll=useRef({}),lastFocus=useRef(null);const open=!!route||timeOpen;const moment=phase(minutes);const Icon=moment.icon;
 useEffect(()=>{const fn=()=>{setRoute(readRoute());setTimeOpen(false);setLightbox(null)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{if(manual)return;const id=setInterval(()=>setMinutes(nowMinutes()),30000);return()=>clearInterval(id)},[manual]);
 const close=()=>{if(lightbox){setLightbox(null);return}if(timeOpen)setTimeOpen(false);else location.hash='/'};
 useLayoutEffect(()=>{if(!open){lastFocus.current?.focus?.();return;}if(!lastFocus.current||!dialog.current?.contains(document.activeElement))lastFocus.current=document.activeElement;const frame=requestAnimationFrame(()=>{dialog.current?.querySelector('button,a,input')?.focus();if(scroll.current)scroll.current.scrollTop=savedScroll.current[route]||0;});return()=>{cancelAnimationFrame(frame);if(scroll.current)savedScroll.current[route]=scroll.current.scrollTop}},[route,timeOpen]);
 useEffect(()=>{if(!open)return;const fn=e=>{if(e.key==='Escape'){e.preventDefault();close();return;}if(e.key==='Tab'){const root=lightbox?document.querySelector('.lightbox'):dialog.current;const targets=[...root.querySelectorAll('button,a[href],input,video,[tabindex="0"]')].filter(e=>!e.disabled&&e.getClientRects().length);const first=targets[0],last=targets.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn)},[open,route,timeOpen,lightbox]);
 useEffect(()=>{if(lightbox)document.querySelector('.lightbox button')?.focus();else if(open)dialog.current?.querySelector('.close-panel')?.focus()},[lightbox]);
 const project=route.startsWith('work/')?projects.find(p=>p.id===route.split('/')[1]):null;
 return <div className={`app ${open?'panel-open':''} ${timeOpen?'time-open':''} ${reduced?'reduced-motion':''}`}>
 <WaterScene minutes={minutes} reduced={reduced} paused={!!route&&!timeOpen} onStatus={setStatus}/>
 <div className="home-ui" inert={open}><header className="home-header"><a href="#/" className="signature" aria-label="Peilin 首页">Peilin.</a><a className="resume-shortcut" href={asset('Peilin-Xie-Resume.pdf')} download>个人简历 <DownloadSimple size={15}/></a></header><nav className="home-nav" aria-label="主导航"><button className="clock-button" onClick={()=>setTimeOpen(true)}><Icon size={15} weight="light"/><span>{timeText(minutes)}</span><small>{manual?'光影时刻':'本地时间'}</small></button><a href="#/about">关于我 <span>About</span></a><a href="#/work">作品集 <span>Selected work</span></a></nav><AudioPlayer videoActive={videoActive}/><footer className="home-footer"><p>用数据理解，<br className="mobile-break"/>用创造回应。</p><button className="scene-caption" onClick={()=>setTimeOpen(true)}><span>STILLWATER · {moment.name}</span><em>{moment.en}</em></button><button className="motion-toggle" onClick={()=>setReduced(v=>!v)} aria-pressed={reduced}><Leaf size={14}/>{reduced?'恢复动效':'减少动效'}</button></footer><p className="scene-status" role="status">{status==='静态水面'?'当前使用静态背景，内容仍可正常浏览。':''}</p></div>
 {open&&<div className={`overlay ${route==='resume'?'resume-overlay':''} ${timeOpen?'time-overlay':''}`} ref={dialog} role="dialog" aria-modal="true" aria-label={timeOpen?'光影时刻':route==='resume'?'完整简历':route==='about'?'关于我':project?project.name:'作品集'}><button className="close-panel" aria-label="关闭面板" onClick={close}><X size={22} weight="light"/></button><div className="overlay-scroll" ref={scroll} inert={!!lightbox}>{timeOpen?<TimePanel {...{minutes,setMinutes,manual,setManual}}/>:route==='about'?<About/>:route==='resume'?<Resume/>:route==='work'?<Work/>:project?<ProjectDetail key={project.id} project={project} onLightbox={setLightbox} onVideo={setVideoActive}/>:<div className="not-found"><h1>这页暂时不在这里。</h1><a href="#/work">返回作品集 <ArrowRight size={18}/></a></div>}</div>{lightbox&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="大图预览"><button aria-label="关闭大图" onClick={()=>setLightbox(null)}><X size={25}/></button><img src={lightbox.src} alt={lightbox.label}/><p>{lightbox.label}</p></div>}</div>}
 </div>;
}
