import {useEffect,useRef,useState} from 'react';
import {Play,Pause,SkipBack,SkipForward,SpeakerHigh,SpeakerSlash,MusicNotes} from '@phosphor-icons/react';
const tracks=[{id:'daybreak',name:'岸边微光',en:'Daybreak'},{id:'drift',name:'浮光之间',en:'Drift'},{id:'moonlit',name:'月色回声',en:'Moonlit'}];
export function AudioPlayer({videoActive}){
 const audio=useRef(null),fade=useRef(0),playingRef=useRef(false),previousVideo=useRef(false),resumeAfterVideo=useRef(false);
 const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[volume,setVolume]=useState(.35),[error,setError]=useState('');
 useEffect(()=>{const a=new Audio();audio.current=a;a.loop=true;a.preload='none';a.src=`${import.meta.env.BASE_URL}assets/audio/${tracks[0].id}.mp3`;a.volume=.35;const pause=()=>{setPlaying(false);playingRef.current=false;};a.addEventListener('pause',pause);const failed=()=>{setError('音频暂不可用，点击重试');pause()};a.addEventListener('error',failed);const visibility=()=>{if(document.hidden)a.pause()};document.addEventListener('visibilitychange',visibility);return()=>{cancelAnimationFrame(fade.current);a.removeEventListener('pause',pause);a.removeEventListener('error',failed);a.pause();a.removeAttribute('src');a.load();document.removeEventListener('visibilitychange',visibility);};},[]);
 useEffect(()=>{if(audio.current)audio.current.volume=volume;},[volume]);
 const start=()=>{const a=audio.current;if(!a)return;setError('');a.volume=volume;return a.play().then(()=>{setPlaying(true);playingRef.current=true;}).catch(()=>{setError('播放未启动，点击重试');setPlaying(false);playingRef.current=false;});};
 useEffect(()=>{if(videoActive&&!previousVideo.current){resumeAfterVideo.current=playingRef.current;audio.current?.pause();}if(!videoActive&&previousVideo.current&&resumeAfterVideo.current){start();resumeAfterVideo.current=false;}previousVideo.current=videoActive;},[videoActive]);
 const change=delta=>{const next=(index+delta+tracks.length)%tracks.length;const wasPlaying=playingRef.current;cancelAnimationFrame(fade.current);audio.current.pause();audio.current.src=`${import.meta.env.BASE_URL}assets/audio/${tracks[next].id}.mp3`;setIndex(next);setError('');if(wasPlaying){audio.current.volume=0;audio.current.play().then(()=>{setPlaying(true);playingRef.current=true;const begin=performance.now();const up=now=>{audio.current.volume=Math.min(1,(now-begin)/500)*volume;if(now-begin<500)fade.current=requestAnimationFrame(up)};fade.current=requestAnimationFrame(up);}).catch(()=>setError('音频暂不可用，点击重试'));}};
 return <section className="music-player" aria-label="环境音乐"><MusicNotes size={17} weight="light"/><p className="track-name">{tracks[index].en}</p><p className="track-caption">{tracks[index].name}</p><div className="music-buttons"><button aria-label="上一首" onClick={()=>change(-1)}><SkipBack size={15} weight="fill"/></button><button aria-label={playing?'暂停环境音乐':'播放环境音乐'} onClick={()=>playing?audio.current.pause():start()}>{playing?<Pause size={16} weight="fill"/>:<Play size={16} weight="fill"/>}</button><button aria-label="下一首" onClick={()=>change(1)}><SkipForward size={15} weight="fill"/></button></div><label className="volume-control">{volume?<SpeakerHigh size={13}/>:<SpeakerSlash size={13}/>}<input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))} aria-label="音乐音量"/></label><span className="audio-status" role="status">{error||(playing?'正在播放 · 原创氛围声景':'点击播放 · 默认静音')}</span></section>;
}
