import {useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowLeft,EnvelopeSimple,Copy,Check,DownloadSimple} from '@phosphor-icons/react';
import {profile,projects,experiences,techStack,awards} from './content';
const asset=p=>`${import.meta.env.BASE_URL}${p}`;
export function HomeIntro(){
 const [index,setIndex]=useState(0);const p=projects[index];
 return <><section className="home-intro" aria-label="个人空间介绍"><p className="intro-label">谢沛霖的个人空间 <span>Portfolio & thoughts</span></p><h1>理解问题，<br/><em>也把想法实现。</em></h1><p className="intro-description">数据科学 · AI 应用 · Agent<br/>在这里，认识我，也看看我做过的作品。</p><a className="intro-link" href="#/work">探索我的作品 <ArrowRight size={18}/></a></section><aside className="floating-feature" aria-label="精选作品"><a href={`#/work/${p.id}`}><img src={asset('projects/'+p.images[0])} alt=""/><span><small>精选作品 · {index+1} / {projects.length}</small><strong>{p.name}</strong><em>{p.category}</em></span><ArrowUpRight size={19}/></a><div className="feature-buttons"><button aria-label="上一个精选作品" onClick={()=>setIndex(i=>(i+projects.length-1)%projects.length)}><ArrowLeft size={14}/></button><button aria-label="下一个精选作品" onClick={()=>setIndex(i=>(i+1)%projects.length)}><ArrowRight size={14}/></button></div></aside></>;
}
export function About(){return <section className="about-page"><div className="about-photo"><img src={asset('portrait.jpg')} alt="谢沛霖证件照"/><span>Peilin Xie</span><small>同济大学 · 2027 届</small></div><div className="about-copy"><p className="personal-kicker">关于我 / About me</p><h1>{profile.name}</h1><p className="about-lead">用数据理解问题，<br/>用 AI 把想法变成产品。</p><p>{profile.introduction}</p><p>我喜欢把复杂问题拆解清楚，再通过实验、模型和实际产品验证想法。从业务分析到独立开发，关注的不只是一个结论，也包括它如何成为下一步行动。</p><div className="about-focus"><span>因果推断</span><span>产品实践</span><span>持续探索</span></div><div className="about-links"><a href="#/journey">经历与成长 <ArrowRight size={16}/></a><a href="#/resume">完整简历 <ArrowUpRight size={16}/></a></div><a className="about-mail" href={`mailto:${profile.email}`}>{profile.email}</a></div></section>}
export function Journey(){return <section className="personal-page journey-page"><p className="personal-kicker">经历与成长 / My journey</p><h1>在真实问题里，<br/><em>积累自己的方法。</em></h1><p className="personal-lead">从数据分析到 AI 应用，把业务理解、实验验证和产品交付连接起来。</p><div className="journey-list">{experiences.map(e=><article key={e.id}><div className="journey-meta"><time>{e.date}</time><img src={asset('companies/'+e.logo)} alt={e.company}/></div><div><h2>{e.company} <span>{e.role}</span></h2><p className="journey-team">{e.team} · {e.location}</p><p>{e.intro}</p><ul>{e.contributions.map(c=><li key={c.title}>{c.title}</li>)}</ul><a href={`#/resume/${e.id}`}>阅读完整经历 <ArrowUpRight size={16}/></a></div></article>)}</div><div className="journey-education"><div><small>2024—2027</small><h2>同济大学</h2><p>管理科学与工程 · 硕士</p></div><div><small>2020—2024</small><h2>苏州大学</h2><p>管理科学与工程 · 本科</p><strong>连续三年专业第一</strong></div></div><h2 className="journey-awards-title">荣誉，也记录着投入</h2><div className="journey-awards">{awards.map(a=><p key={a.title}><span>{a.title}</span><small>{a.prize||a.type}</small></p>)}</div></section>}
export function Approach(){return <section className="personal-page approach-page"><p className="personal-kicker">我的方法 / How I work</p><h1>先理解，动手构建，<br/><em>再认真验证。</em></h1><p className="personal-lead">在分析与创造之间，形成可以复用、可以解释的工作方式。</p><div className="method-list">{[{title:'把问题问清楚',text:profile.selfEvaluation[0],evidence:'实习中的增长分析、实验设计与因果推断',url:'#/journey'},{title:'把方法变成工具',text:profile.selfEvaluation[1],evidence:'智帧华象 · WorkRelay · Colla Agent',url:'#/work'},{title:'把结果交付完整',text:profile.selfEvaluation[2],evidence:'完整背景、实现过程与项目产物',url:'#/work'}].map((m,i)=><article key={m.title}><span className="method-number">0{i+1}</span><div><h2>{m.title}</h2><p>{m.text}</p><a href={m.url}>{m.evidence}<ArrowUpRight size={16}/></a></div></article>)}</div><h2 className="tools-heading">使用的工具与技术</h2><div className="tools-list">{techStack.map(t=><div key={t.title}><h3>{t.title}</h3><p>{t.items.join(' · ')}</p></div>)}</div></section>}
export function Contact(){const [copied,setCopied]=useState(false),[message,setMessage]=useState('');const copy=async()=>{try{await navigator.clipboard.writeText(profile.email);setCopied(true);setMessage('邮箱已复制');}catch{setMessage('请长按或选中下方邮箱复制');}};return <section className="contact-page"><p className="personal-kicker">联系我 / Get in touch</p><h1>让交流，<br/><em>从一个具体问题开始。</em></h1><p>关于数据科学、AI 应用、Agent 工作流，<br/>或者你想进一步了解的某个项目。</p><a className="contact-email" href={`mailto:${profile.email}`}><EnvelopeSimple size={25}/>{profile.email}</a><div className="contact-primary"><a href={`mailto:${profile.email}`}>写封邮件 <ArrowUpRight size={17}/></a><button onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>}复制邮箱</button></div><p className="copy-status" role="status">{message}</p><div className="contact-resources"><a href={asset('Peilin-Xie-Resume.pdf')} download><span>下载简历<small>了解教育、经历与能力</small></span><DownloadSimple size={21}/></a><a href={profile.github} target="_blank" rel="noreferrer"><span>GitHub<small>查看开源项目与代码</small></span><ArrowUpRight size={21}/></a><a href="#/work"><span>作品集<small>六个项目，完整过程与展示</small></span><ArrowRight size={21}/></a></div></section>}
