import {profile,experiences,skills,techStack,awards} from './content';
import {ArrowUpRight,DownloadSimple,EnvelopeSimple} from '@phosphor-icons/react';
const asset=p=>`${import.meta.env.BASE_URL}${p}`;
function Metrics({items}){return <div className="resume-metrics">{items.map(m=><div key={m.label}><strong>{m.value}</strong><span>{m.label}</span>{m.note&&<small>{m.note}</small>}</div>)}</div>}
export function Resume(){return <article className="resume-paper"><header className="resume-header"><div><span className="eyebrow">RESUME · 2027</span><h1>谢沛霖 <small>Peilin Xie</small></h1><p>{profile.introduction}</p><a href={asset('Peilin-Xie-Resume.pdf')} download className="paper-link">下载完整简历 <DownloadSimple size={17}/></a></div><img className="resume-portrait" src={asset('portrait.jpg')} alt="谢沛霖证件照"/></header><nav className="resume-jumps" aria-label="简历章节">{[['教育背景','education'],['实习经历','experience'],['技能','skills'],['荣誉奖项','honors'],['联系','contact']].map(([name,id])=><button key={id} onClick={()=>document.getElementById('resume-'+id)?.scrollIntoView({behavior:document.querySelector('.reduced-motion')?'instant':'smooth',block:'start'})}>{name}</button>)}</nav>
<section id="resume-education"><h2>教育背景</h2><div className="school-grid"><article><div className="school-title"><img src={asset('schools/tongji.png')} alt="同济大学校徽"/><div><h3>同济大学 <small>985</small></h3><span>经济与管理学院 · 2024.09–2027.03</span></div></div><h4>管理科学与工程</h4><p>工业工程与管理硕士</p><div className="academic-scores"><span>GPA <b>4.8 / 5.0</b></span><span>专业排名 <b>Top 1%</b></span></div></article><article><div className="school-title"><img src={asset('schools/soochow.webp')} alt="苏州大学校徽"/><div><h3>苏州大学 <small>211</small></h3><span>管理学院 · 2020.09–2024.06</span></div></div><h4>管理科学与工程</h4><p>本科 · 保送同济大学</p><div className="academic-scores"><span>GPA <b>4.0 / 4.0</b></span><span>专业排名 <b>1 / 95</b></span></div><strong className="rank-streak">连续三年专业第一</strong><p className="school-awards">本科生国家奖学金 · 苏州大学学业特等奖学金<br/>美国大学生数学建模竞赛 F 题特等奖提名奖</p></article></div><div className="shared-courses"><h4>核心课程</h4><p>高级运筹学、优化理论、多元统计、Python 基础、数据库原理、机器学习算法、系统工程与方法</p></div></section>
<section><h2>能力优势与自我评价</h2><div className="strength-grid">{profile.strengths.map(s=><div key={s.title}><h3>{s.title}</h3><p>{s.text}</p></div>)}</div>{profile.selfEvaluation.map(p=><p key={p}>{p}</p>)}</section>
<section id="resume-experience"><h2>实习经历</h2>{experiences.map(e=><article className="resume-experience" id={'experience-'+e.id} key={e.id}><header><div><img className="employer-logo" src={asset('companies/'+e.logo)} alt={e.company}/><h3>{e.company} <span>{e.role}</span></h3><p>{e.team}</p></div><span className="experience-date">{e.date}<br/>{e.location}</span></header><p className="experience-intro">{e.intro}</p>{e.metrics&&<Metrics items={e.metrics}/>} {e.comparison&&<div className="comparison">{e.comparison.map(g=><div key={g.audience}><h4>{g.audience} · {g.direction}</h4><p>{g.description}</p></div>)}</div>}{e.contributions.map(c=><div className="resume-contribution" key={c.title}><span className="content-label">{c.label}</span><h4>{c.title}</h4>{c.paragraphs.map(p=><p key={p}>{p}</p>)}{c.workflow&&<p className="workflow-text">{c.workflow.join(' → ')}</p>}<div className="result-callout"><strong>项目成果</strong><p>{c.result}</p></div></div>)}{e.caseStudy&&<div className="case-study"><span className="content-label">代表业务项目 · {e.caseStudy.period}</span><h4>{e.caseStudy.title}</h4><p>{e.caseStudy.description}</p>{e.caseStudy.steps.map(s=><div key={s.title}><h5>{s.title}</h5><p>{s.text}</p></div>)}<Metrics items={e.caseStudy.results}/><p>{e.caseStudy.conclusion}</p></div>}</article>)}</section>
<section id="resume-skills"><h2>技能</h2><div className="skill-grid">{skills.map(s=><article key={s.title}><h3>{s.title}</h3><p>{s.description||s.text}</p>{s.items&&<ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul>}{s.evidence&&<p>{s.evidence}</p>}</article>)}</div><h3 className="stack-title">技术栈</h3><div className="skill-grid">{techStack.map(s=><article key={s.title}><h4>{s.title}</h4><p>{s.items.join(' · ')}</p></article>)}</div></section>
<section id="resume-honors"><h2>荣誉奖项</h2><div className="honor-list">{awards.map(a=><article key={a.title}><div><h3>{a.title}</h3>{a.prize&&<p>{a.prize}</p>}</div><span>{a.type}</span></article>)}</div></section>
<section id="resume-contact"><h2>联系与简历</h2><p>关注数据科学、AI 应用与 Agent 工作流，期待围绕真实业务问题交流，也欢迎了解我的项目实践。</p><div className="contact-actions"><a href={`mailto:${profile.email}`}><EnvelopeSimple size={18}/>{profile.email}</a><a href={profile.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={18}/></a><a href="https://w48669664-bit.github.io/" target="_blank" rel="noreferrer">简历版网站 <ArrowUpRight size={18}/></a></div></section></article>}
